CREATE TABLE planning_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL,
    version_number INT NOT NULL,
    design_spec CLOB,
    implementation_plan CLOB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    provider VARCHAR(40),
    model VARCHAR(120),
    revision_feedback CLOB,
    state VARCHAR(20) NOT NULL,
    approved_at TIMESTAMP,
    CONSTRAINT fk_planning_version_issue FOREIGN KEY (issue_id) REFERENCES tracked_issues(id),
    CONSTRAINT uq_planning_version_number UNIQUE (issue_id, version_number)
);

ALTER TABLE tracked_issues ADD COLUMN approved_planning_version_id BIGINT;
ALTER TABLE tracked_issues ADD COLUMN plan_conformance_attempt INT DEFAULT 0 NOT NULL;
ALTER TABLE tracked_issues ADD COLUMN plan_correction_pending BOOLEAN DEFAULT FALSE NOT NULL;

INSERT INTO planning_versions
    (issue_id, version_number, design_spec, implementation_plan, created_at,
     provider, model, revision_feedback, state, approved_at)
SELECT id, 1, NULL, implementation_plan, updated_at,
       resolved_agent_provider, resolved_impl_model, plan_feedback, 'LEGACY',
       CASE WHEN plan_approved THEN updated_at ELSE NULL END
FROM tracked_issues
WHERE implementation_plan IS NOT NULL;

UPDATE tracked_issues t
SET approved_planning_version_id = (
    SELECT p.id FROM planning_versions p
    WHERE p.issue_id = t.id AND p.version_number = 1
)
WHERE t.plan_approved = TRUE AND t.implementation_plan IS NOT NULL;

ALTER TABLE tracked_issues ADD CONSTRAINT fk_issue_approved_plan
    FOREIGN KEY (approved_planning_version_id) REFERENCES planning_versions(id);

UPDATE watched_repos SET plan_first = TRUE;
ALTER TABLE watched_repos ALTER COLUMN plan_first SET DEFAULT TRUE;
