CREATE TABLE decomposition_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id BIGINT NOT NULL,
    parent_issue_id BIGINT NOT NULL,
    state VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    released_at TIMESTAMP,
    release_reason VARCHAR(2000),
    released_by VARCHAR(255),
    attention_reason VARCHAR(2000),
    last_error VARCHAR(4000),
    last_reconciled_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_decomposition_group_repo FOREIGN KEY (repo_id) REFERENCES watched_repos(id) ON DELETE CASCADE,
    CONSTRAINT fk_decomposition_group_parent FOREIGN KEY (parent_issue_id) REFERENCES tracked_issues(id) ON DELETE CASCADE,
    CONSTRAINT uk_decomposition_group_parent UNIQUE (parent_issue_id)
);

CREATE TABLE decomposition_children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    sequence_position INTEGER NOT NULL,
    proposed_title VARCHAR(500) NOT NULL,
    proposed_body CLOB NOT NULL,
    external_key VARCHAR(255) NOT NULL,
    github_issue_number INTEGER,
    tracked_issue_id BIGINT,
    creation_state VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_decomposition_child_group FOREIGN KEY (group_id) REFERENCES decomposition_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_decomposition_child_tracked FOREIGN KEY (tracked_issue_id) REFERENCES tracked_issues(id),
    CONSTRAINT uk_decomposition_child_position UNIQUE (group_id, sequence_position),
    CONSTRAINT uk_decomposition_child_external UNIQUE (external_key),
    CONSTRAINT uk_decomposition_child_tracked UNIQUE (tracked_issue_id),
    CONSTRAINT uk_decomposition_child_github UNIQUE (group_id, github_issue_number)
);

CREATE INDEX idx_decomposition_group_repo_state ON decomposition_groups(repo_id, state);
CREATE INDEX idx_decomposition_child_group_position ON decomposition_children(group_id, sequence_position);
