ALTER TABLE watched_repos ADD COLUMN workflow_policy VARCHAR(32) NOT NULL DEFAULT 'LEGACY';
ALTER TABLE watched_repos ADD COLUMN approval_stages VARCHAR(255) NOT NULL DEFAULT 'PLANNING,IMPLEMENTATION,VERIFICATION,REVIEW,MERGE';
ALTER TABLE tracked_issues ADD COLUMN workflow_policy VARCHAR(32);
ALTER TABLE tracked_issues ADD COLUMN approval_stages VARCHAR(255);
ALTER TABLE tracked_issues ADD COLUMN workflow_run INTEGER NOT NULL DEFAULT 0;
UPDATE tracked_issues SET workflow_policy = 'LEGACY' WHERE status NOT IN ('PENDING', 'QUEUED');

CREATE TABLE stage_approvals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL,
    run_number INTEGER NOT NULL DEFAULT 0,
    stage VARCHAR(32) NOT NULL,
    attempt INTEGER NOT NULL,
    state VARCHAR(32) NOT NULL,
    provider VARCHAR(32),
    model VARCHAR(255),
    artifact_version_id BIGINT NOT NULL DEFAULT 0,
    actor VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at TIMESTAMP,
    CONSTRAINT fk_stage_approval_issue FOREIGN KEY (issue_id) REFERENCES tracked_issues(id) ON DELETE CASCADE,
    CONSTRAINT uk_stage_approval_attempt UNIQUE (issue_id, run_number, stage, attempt, artifact_version_id)
);
CREATE INDEX idx_stage_approval_pending ON stage_approvals(issue_id, state);
ALTER TABLE iterations ADD COLUMN reviewed_commit_sha VARCHAR(64);
