CREATE TABLE issue_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL,
    repo_id BIGINT,
    workflow_run VARCHAR(200),
    source_key VARCHAR(200) NOT NULL UNIQUE,
    actor VARCHAR(40) NOT NULL,
    action VARCHAR(40) NOT NULL,
    outcome VARCHAR(40) NOT NULL,
    reason VARCHAR(40),
    plan_version_id BIGINT,
    iteration_id BIGINT,
    stage_approval_id BIGINT,
    guidance_id BIGINT,
    pr_number INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_issue_decisions_history ON issue_decisions(issue_id, created_at DESC, id DESC);

-- A terminal ledger lock, not a domain/control lock. Also records the honest tracking boundary.
CREATE TABLE decision_history_boundary (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO decision_history_boundary(id) VALUES (1);
