CREATE TABLE operator_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL,
    scope_key VARCHAR(200) NOT NULL,
    kind VARCHAR(40) NOT NULL,
    state VARCHAR(20) NOT NULL
);
CREATE INDEX idx_operator_transition_scope ON operator_transitions(issue_id, scope_key, kind, id);
ALTER TABLE stage_approvals ADD COLUMN decision_generation BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE processing_control ADD COLUMN transition_generation BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE issue_guidance ADD COLUMN request_token VARCHAR(80);
CREATE UNIQUE INDEX idx_guidance_request ON issue_guidance(issue_id, request_token);
