ALTER TABLE watched_repos ADD COLUMN execution_permissions VARCHAR(30) NOT NULL DEFAULT 'ASK';
ALTER TABLE tracked_issues ADD COLUMN waiting_for_input BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE harness_run_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL REFERENCES tracked_issues(id) ON DELETE CASCADE,
    workflow_run INTEGER NOT NULL,
    policy VARCHAR(30) NOT NULL,
    UNIQUE(issue_id, workflow_run)
);
CREATE TABLE harness_input_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL REFERENCES tracked_issues(id) ON DELETE CASCADE,
    workflow_run INTEGER NOT NULL,
    iteration_num INTEGER NOT NULL,
    harness VARCHAR(40) NOT NULL,
    transport_id VARCHAR(80) NOT NULL,
    native_id VARCHAR(160) NOT NULL,
    session_id VARCHAR(160),
    method VARCHAR(80) NOT NULL,
    payload TEXT NOT NULL,
    response TEXT,
    state VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    answered_at TIMESTAMP,
    UNIQUE(transport_id, native_id)
);
CREATE INDEX idx_harness_input_issue ON harness_input_requests(issue_id, id);
